#
# This file was generated by bqtinstaller.py (bazel qt installer)
# To update run: bazel run @//:qt_install_x86_64.update
#

QT_MODULES = {
    "qt3d": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.addons.qt3d.gcc_64/6.4.0-0-202209270704qt3d-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "d8b34d32549b42b51785675d73ee593a968f9225b9e8ddbed1a294cb27c3b156"
    },
    "qtcharts": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.addons.qtcharts.gcc_64/6.4.0-0-202209270704qtcharts-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "ee4fc2285c49496e1966557642c1a961fd989081ccfd81430b750b7bf2b84ad4"
    },
    "qtconnectivity": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.addons.qtconnectivity.gcc_64/6.4.0-0-202209270704qtconnectivity-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "294542a2b89dd48a2d22085e85d5097b72975cb82c1a445bbaf0e3982aad41f6"
    },
    "qtdatavis3d": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.addons.qtdatavis3d.gcc_64/6.4.0-0-202209270704qtdatavis3d-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "899e068b861543059467bbf12b43ccf4f0d60d13befe31ecfe62392f18b0c7ba"
    },
    "qthttpserver": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.addons.qthttpserver.gcc_64/6.4.0-0-202209270704qthttpserver-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "61ff18911a078b8b25420a86e4728d5f51f30b3a3ee211e660d31cd7486b8d32"
    },
    "qtimageformats": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.addons.qtimageformats.gcc_64/6.4.0-0-202209270704qtimageformats-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "657f6af0fe3c489b6b413528918b1f055f6e047d75776a3b9b2e697e349d0477"
    },
    "qtlanguageserver": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.addons.qtlanguageserver.gcc_64/6.4.0-0-202209270704qtlanguageserver-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "c25001d10161bc31a76348c44ed8244338849a17d66d4c4ee54ebcb14e98463f"
    },
    "qtlottie": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.addons.qtlottie.gcc_64/6.4.0-0-202209270704qtlottie-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "2747018803b7b972bd9c76d775ecc6d296fd44eee4dc4f50da75cf08d6126c0a"
    },
    "qtmultimedia": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.addons.qtmultimedia.gcc_64/6.4.0-0-202209270704qtmultimedia-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "53a29965311700c50d124856ddb80980ca8e8de14acf7f0cf13682099f361778"
    },
    "qtnetworkauth": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.addons.qtnetworkauth.gcc_64/6.4.0-0-202209270704qtnetworkauth-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "f3ac84b94ad4869e41d4b6767d62dbe6a5ccb6e1c262b31db638b5e7f4064fd1"
    },
    "qtpdf": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.addons.qtpdf.gcc_64/6.4.0-0-202209270704qtpdf-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "055bf9f904e44a89ef6d9c540fd180e3854f8792045c147323c722f16f624eb6"
    },
    "qtpositioning": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.addons.qtpositioning.gcc_64/6.4.0-0-202209270704qtpositioning-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "fe3aa78d23496c0f89310239fe96f1b150a53bebd29e86608737f9b1072ff7fc"
    },
    "qtquick3dphysics": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.addons.qtquick3dphysics.gcc_64/6.4.0-0-202209270704qtquick3dphysics-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "e0fc383db0cd80060ba38dbee2959b083aaa6c3d59bd4ba107976f4e2a1b9019"
    },
    "qtremoteobjects": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.addons.qtremoteobjects.gcc_64/6.4.0-0-202209270704qtremoteobjects-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "17c3de554a9f7f2f87946d519d66b837cb679779af74ad3857f97097b6fc08b3"
    },
    "qtscxml": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.addons.qtscxml.gcc_64/6.4.0-0-202209270704qtscxml-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "6128bc05ad7109cef4aaef51723f07447bfc6b8ed8da636caf340a36969bb62c"
    },
    "qtsensors": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.addons.qtsensors.gcc_64/6.4.0-0-202209270704qtsensors-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "8cbb0e481ffc8cca16fe00800e104dd5effecdabbead2366add51d2c3fbfb183"
    },
    "qtserialbus": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.addons.qtserialbus.gcc_64/6.4.0-0-202209270704qtserialbus-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "604e847072750d992c2f068334a9c13497ca601c9d3a45573f6970a50cfae67b"
    },
    "qtserialport": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.addons.qtserialport.gcc_64/6.4.0-0-202209270704qtserialport-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "216e603e20ef82478b4a04f6226ba6a4488b0ea92a03349abcf9812914a8f4b0"
    },
    "qtspeech": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.addons.qtspeech.gcc_64/6.4.0-0-202209270704qtspeech-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "a4b2e50db40f1e290acd794fdf17dd956cba17d5a20d29d93e94c10176198032"
    },
    "qtvirtualkeyboard": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.addons.qtvirtualkeyboard.gcc_64/6.4.0-0-202209270704qtvirtualkeyboard-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "8e087e5c68b1e0009ce065ef03aa38a64ebc83b64d11f697f68811c963de9edf"
    },
    "qtwebchannel": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.addons.qtwebchannel.gcc_64/6.4.0-0-202209270704qtwebchannel-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "46b91fa1e2d2e20e2d52522012e8704b6911c1bca2de30cea256f037c5d34cac"
    },
    "qtwebengine": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.addons.qtwebengine.gcc_64/6.4.0-0-202209270704qtwebengine-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "dd4740fed3816fc9cab30d22397ccd81bfcf43ffbd7b0997012b96ebc999d680"
    },
    "qtwebsockets": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.addons.qtwebsockets.gcc_64/6.4.0-0-202209270704qtwebsockets-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "3e523e029f18b991a078e818418430d76a1b9e8d0a3ffb1d00f3101a34762996"
    },
    "qtwebview": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.addons.qtwebview.gcc_64/6.4.0-0-202209270704qtwebview-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "5e681a2190c49e108ae1b91f2d160171e3ad0bde4e120ca6b4d01e1be1b745c0"
    },
    "qtbase": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.gcc_64/6.4.0-0-202209270704qtbase-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "247952825916fab207d258c41ddf1a5c0ab0007c7c02940fa995a4ead5cc03ea"
    },
    "qtsvg": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.gcc_64/6.4.0-0-202209270704qtsvg-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "96db59549864a205c83b0e4a7095c7d8a868af6930ce791f2df79b2fcb3245f1"
    },
    "qtdeclarative": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.gcc_64/6.4.0-0-202209270704qtdeclarative-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "ffebc23f2afa5cb75b7d59f9b2b1bf28a7120bf2b16ead2ad32e49812b9cd8f8"
    },
    "qttools": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.gcc_64/6.4.0-0-202209270704qttools-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "9c0eb05e86e129e38643af6fa17e5dfe75d5b49e8e1bbef2baa348066537efb7"
    },
    "qttranslations": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.gcc_64/6.4.0-0-202209270704qttranslations-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "72a644c4e6de3bdcbb8e85b8790b10858405c876ba19feac95a5b5087b72da18"
    },
    "qtwayland": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.qtwaylandcompositor.gcc_64/6.4.0-0-202209270704qtwayland-compositor-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "f902214a1ab83cfd5f1399ffefca9d45f1763b14acebcc2e0abcde279be98efb"
    },
    "icu": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.gcc_64/6.4.0-0-202209270704icu-linux-Rhel7.2-x64.7z",
        "sha256": "2ca8e8fb1af43cfd654bf89f82b1cc8d3d7bcb30db52ee0181231f7a2692a5d3"
    },
    "qt5compat": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.qt5compat.gcc_64/6.4.0-0-202209270704qt5compat-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "03d71fb047a5e1dc5fe80a633f8b628ebd75f0d6052931fb82c6a8c858b0cfbe"
    },
    "qtquick3d": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.qtquick3d.gcc_64/6.4.0-0-202209270704qtquick3d-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "108c375d2c1b743f3cece096f7f256dc46a9b99f3bd6e70e8427e06ba4f5ed92"
    },
    "qtquicktimeline": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.qtquicktimeline.gcc_64/6.4.0-0-202209270704qtquicktimeline-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "deeb73bcfae72a40676187058dab814ed8e8515f997176cf5a5f23d57c69ea46"
    },
    "qtshadertools": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.qtshadertools.gcc_64/6.4.0-0-202209270704qtshadertools-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "23e7231917cee000350c85c3f7d6018df6f7a67ebe4ef3c0bbff51c69bbd118d"
    }
}
